### ISSUE TITLE
Python, still?

### ISSUE THREAD

**Issue by dokato** [CaRdiffR/nounprojectR#8]
Hi guys @DaveParr @brennanpincardiff !

Do you still rely on Python for OAuth, cause I still see some code there?

I thought that this https://github.com/r-lib/httr/issues/542 made it work. At least it worked for me last time when I checked that.

**Comment by DaveParr** [comment]
It did :)

check:
https://github.com/CaRdiffR/nounprojectR/commit/76be9e877d0e68b936193527fd60349d804d4988

Python is still in the codebase as we basically just havn't got to removing it yet. I split it into it's own file 
 though here:
https://github.com/CaRdiffR/nounprojectR/commit/141865c6eee1366533ffc0206fcc545cbeb923c7

Current R implemntation is as so

- use [ `np_credentials()`](https://github.com/CaRdiffR/nounprojectR/blob/master/R/np_credentials.R) to set your key, token and ap name as Sys environment variables once per session
- use [`make_endpoints()`](https://github.com/CaRdiffR/nounprojectR/blob/master/R/make_endpoints.R) to construct the relevant url to search by term or specfiy by id
- use [`get_nouns_api()`](https://github.com/CaRdiffR/nounprojectR/blob/master/R/get_nouns_api.R) to source the items from the endpoint via the api.

No python! :tada:

**Comment by dokato** [comment]
Cool, nice to know!
